version: "2"

services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./nginx_ssl:/etc/nginx/ssl
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot/${DOMAIN}
      - ./html:/var/www/html/${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    env_file:
      - ./config.env
    volumes:
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot/${DOMAIN}
    depends_on:
      - nginx
