version: "2"

services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./nginx_ssl:/etc/nginx/ssl
      - ./certbot_certs:/etc/letsencrypt
      - ./cerias_b01lers_com_certbot:/var/www/certbot/cerias.b01lers.com
      - ./html:/var/www/html/cerias.b01lers.com
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    env_file:
      - ./config.env
    volumes:
      - ./certbot_certs:/etc/letsencrypt
      - ./cerias_b01lers_com_certbot:/var/www/certbot/cerias.b01lers.com
    depends_on:
      - nginx
